spring:
  datasource:
    username: postgres
    password: 12345678
    url: jdbc:postgresql://localhost:5433/postgres
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        globally_quoted_identifiers: true
  properties:
    hibernate:
      default-schema: "public"
  hibernate:
    generate-ddl: true
  flyway:
    enabled: true